name: Python Build and Test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print a message
        run: echo "Hello, this is the build and test workflow!"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests random2

      - name: Add final_project_code directory to Python path
        run: python -c "import sys; sys.path.append('final_project_code');"
        
      - name: Run passwordLogic test
        run: python -m unittest final_project_code.test_api.password_tests_api.passwordTests
          

      
