name: Python Build and Test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print a message
        run: echo "Hello, this is the build and test workflow!"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests random2

      - name: Run passwordLogic test
        run: |
          python -c "import unittest; from logic_api.password_logic_api import passwordLogic; \
          loader = unittest.TestLoader(); suite = loader.loadTestsFromTestCase(passwordLogic); \
          runner = unittest.TextTestRunner(); result = runner.run(suite); \
          exit(not result.wasSuccessful())"

      
